"""ZeroMQ CURVE encryption + authentication for the FBP wire (opt-in).

This closes the documented "#1 production gap" in
``docs/transport_trust_boundary.md`` §3 (no encryption on ``tcp://``/``ipc://``)
using ZeroMQ's native **CURVE** mechanism — the dependency-free symmetric-key
encryption + peer-auth layer built into libzmq/pyzmq.

**Why CURVE and not stdlib ``ssl``?** The FBP wire is ZeroMQ multipart frames,
not raw Python ``socket``s. ZeroMQ owns the connection/framing, so stdlib
``ssl`` cannot transparently wrap it. CURVE is libzmq's native encryption for
exactly this situation — it encrypts every frame on the wire and authenticates
peers — and needs no new dependency.

**Key delivery (out-of-band by the driver).** CURVE uses distinct keypairs, so
the two sides of a link must know each other's public key. The driver is the
single authority: it generates one server keypair + one client keypair and hands
the needed key to each child via its ``AgentConfig``. The public keys travel on
the config (an in-process/loopback channel the operator already controls), never
over the encrypted wire.

Design (consistent with the project's posture):

- **Opt-in, default off.** A driver/agent only enables CURVE when given a
  ``CurveConfig``. Without it, sockets are untouched (backward compatible).
- **Fail-closed.** A component sets the CURVE options before bind/connect. A
  peer without the correct key cannot establish a link; an unauthorized client
  (missing from the ZAP allowlist) is rejected. There is no plaintext fallback.
- **Whole-tree inheritance.** Children receive their keys from the parent config,
  so the entire tree speaks one protected wire.

This module is pure and offline (derives keys, returns socket options, writes
the ZAP allowlist certs). libzmq performs the encrypted handshake.
"""

from __future__ import annotations

import os
import shutil
import tempfile
from dataclasses import dataclass
from typing import Any, Final

import zmq
import zmq.auth
import zmq.auth.thread
from zmq import Socket

#: The CURVE mechanism tag (v1).
CURVE_TAG: Final = "fbp-curve-v1"


@dataclass(frozen=True)
class CurveConfig:
    """Operator-supplied CURVE material for a driver session.

    ``server_public`` / ``server_secret`` is the root (binder) keypair.
    ``client_public`` / ``client_secret`` is the client (connector) keypair any
    child uses to connect to the root. Both keypairs are generated by the driver
    (or supplied by the operator) and distributed via config.
    """

    server_public: bytes
    server_secret: bytes
    client_public: bytes
    client_secret: bytes


def generate_curve_config() -> CurveConfig:
    """Generate a fresh CURVE session (server + client keypairs)."""
    srv_pub, srv_sec = zmq.curve_keypair()
    cli_pub, cli_sec = zmq.curve_keypair()
    return CurveConfig(
        server_public=srv_pub,
        server_secret=srv_sec,
        client_public=cli_pub,
        client_secret=cli_sec,
    )


def server_options(cfg: CurveConfig) -> dict[str, object]:
    """Socket options making a ROUTER a CURVE server for ``cfg``."""
    return {
        "curve_server": True,
        "curve_publickey": cfg.server_public,
        "curve_secretkey": cfg.server_secret,
    }


def client_options(cfg: CurveConfig) -> dict[str, object]:
    """Socket options making a DEALER a CURVE client of ``cfg``'s server."""
    return {
        "curve_server": False,
        "curve_publickey": cfg.client_public,
        "curve_secretkey": cfg.client_secret,
        "curve_serverkey": cfg.server_public,
    }


_OPTIONS: dict[str, int] = {
    "curve_server": zmq.CURVE_SERVER,
    "curve_publickey": zmq.CURVE_PUBLICKEY,
    "curve_secretkey": zmq.CURVE_SECRETKEY,
    "curve_serverkey": zmq.CURVE_SERVERKEY,
}


def apply_options(socket: Socket[Any], opts: dict[str, object]) -> None:
    for name, value in opts.items():
        opt = _OPTIONS.get(name)
        if opt is None:
            raise KeyError(f"unknown CURVE socket option {name!r}")
        if isinstance(value, bool):
            socket.setsockopt(opt, int(value))
        else:
            socket.setsockopt(opt, value)  # type: ignore[arg-type]


def write_public_cert(path: str, public_z85: bytes) -> None:
    """Write a ZAP public certificate authorizing ``public_z85``."""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("metadata\ncurve\n")
        fh.write(f'    public-key = "{public_z85.decode("ascii")}"\n')


class CurveAuth:
    """A fail-closed ZAP authenticator allowlisting exactly the derived keys.

    ``start`` writes the allowlist certificates (from ``allowed``), starts the
    ZAP thread, and configures ``domain="*"`` so every incoming connection is
    checked against it. A client public key missing from the allowlist is
    rejected. ``stop`` is idempotent and removes the temp allowlist dir.
    """

    def __init__(self, context: Any) -> None:
        self._auth = zmq.auth.thread.ThreadAuthenticator(context)
        self._dir: str | None = None

    def start(self, *, allowed: list[bytes]) -> None:
        self._dir = tempfile.mkdtemp(prefix="fbp-curve-")
        for i, pub in enumerate(allowed):
            write_public_cert(os.path.join(self._dir, f"peer-{i}.key"), pub)
        self._auth.start()
        self._auth.configure_curve(domain="*", location=self._dir)

    def stop(self) -> None:
        import contextlib

        with contextlib.suppress(Exception):
            self._auth.stop()
        if self._dir is not None:
            shutil.rmtree(self._dir, ignore_errors=True)
            self._dir = None