"""Agent-centric: a deterministic control plane for governed, verifiable agents.

Public surface is intentionally minimal. The primary entry point is
``AgentManager`` from the control-plane package; contracts live in
``agent_centric.contracts``.
"""

from .agents import ToolContext, ToolRequest, ToolResult
from .contracts import (
    AcceptResult,
    AgendaEntry,
    AgentComponentManifest,
    AgentManifestVersion,
    Bill,
    BillDraft,
    BillLine,
    BillsRegistry,
    BillsRegistryVersion,
    BillStatus,
    BillTotal,
    BillVersion,
    CalendarProjection,
    Capability,
    CpmMetric,
    CpmVersion,
    CriticalPathResult,
    CriticalPathStage,
    DraftProposals,
    EmailList,
    EmailMessage,
    EmailVersion,
    Failure,
    FailureReason,
    InboxEntry,
    InboxInventory,
    IntakeVersion,
    MessageSummary,
    ModelProvider,
    ModelProviderError,
    ModelProviderVersion,
    ModelResponse,
    ModelSummary,
    ParallelComposition,
    ParallelVersion,
    PipelineVersion,
    Policy,
    PolicyDecision,
    PolicySummary,
    PolicyVersion,
    RegistryBill,
    ReplayDiff,
    ReplayResult,
    ReplayVersion,
    ResourceEnvelope,
    RunState,
    SequentialComposition,
    StageKind,
    StageSpec,
    StageSummary,
    StepRecord,
    StepStatus,
    SummaryVersion,
    TaskSpecification,
    TaskSpecVersion,
    ToolDescriptor,
    ToolSummary,
    ToolVersion,
    Trajectory,
    TrajectorySummary,
    TrajectoryVersion,
    VerifiedResult,
    VerifiedResultVersion,
    WorkspaceEntry,
    WorkspaceEntryKind,
    WorkspaceLayout,
    WorkspaceVersion,
)
from .control_plane import (
    AgentExecutionError,
    AgentManager,
    BillsOps,
    EmailTools,
    ExecutionBackend,
    InProcessBackend,
    IntakeOps,
    LocalMcpServer,
    McpProtocolError,
    McpTimeoutError,
    McpToolAdapter,
    McpToolCallError,
    McpToolError,
    Outcome,
    Registry,
    SubprocessBackend,
    ToolExecutionError,
    ToolRegistry,
    Workspace,
    WorkspaceError,
    analyse_critical_path,
    ensure_bills_layout,
    ensure_intake_layout,
)

# The flow-based-programming (FBP) subsystem: a rooted, recursive tree of
# agents over the directive/response protocol. Exported additively so the
# existing control-plane surface is untouched.
from .fbp import (
    Agent as FbpAgent,
)
from .fbp import (
    AgentConfig as FbpAgentConfig,
)
from .fbp import (
    Context as FbpContext,
)
from .fbp import (
    Directive as FbpDirective,
)
from .fbp import (
    FbpDriver,
)
from .fbp import (
    Response as FbpResponse,
)
from .fbp import (
    Shell as FbpShell,
)
from .fbp import (
    register_callable as fbp_register_callable,
)
from .providers import (
    EmailGatewayError,
    FailingStubModelProvider,
    FakeEmailGateway,
    OptionalRealEmailGateway,
    OptionalRealModelProvider,
    StubModelProvider,
    build_optional_email_gateway,
    build_real_model_provider,
    redact_secrets,
)

__all__ = [
    "AgentManager",
    "Outcome",
    "Registry",
    "ExecutionBackend",
    "InProcessBackend",
    "SubprocessBackend",
    "AgentExecutionError",
    "McpToolAdapter",
    "McpToolError",
    "McpProtocolError",
    "McpToolCallError",
    "McpTimeoutError",
    "LocalMcpServer",
    "ToolContext",
    "ToolRequest",
    "ToolResult",
    "ToolRegistry",
    "ToolExecutionError",
    "AgentComponentManifest",
    "AgentManifestVersion",
    "Bill",
    "BillLine",
    "BillTotal",
    "BillVersion",
    "Capability",
    "CpmMetric",
    "CpmVersion",
    "CriticalPathResult",
    "CriticalPathStage",
    "Failure",
    "FailureReason",
    "ModelProvider",
    "ModelProviderError",
    "ModelProviderVersion",
    "ModelResponse",
    "StubModelProvider",
    "FailingStubModelProvider",
    "OptionalRealModelProvider",
    "build_real_model_provider",
    "redact_secrets",
    "analyse_critical_path",
    "ParallelComposition",
    "ParallelVersion",
    "PipelineVersion",
    "Policy",
    "PolicyDecision",
    "PolicyVersion",
    "ReplayResult",
    "ReplayDiff",
    "ReplayVersion",
    "ResourceEnvelope",
    "SequentialComposition",
    "StageSpec",
    "StepRecord",
    "StepStatus",
    "TaskSpecification",
    "TaskSpecVersion",
    "ToolDescriptor",
    "ToolVersion",
    "Trajectory",
    "TrajectoryVersion",
    "VerifiedResult",
    "VerifiedResultVersion",
    "TrajectorySummary",
    "SummaryVersion",
    "RunState",
    "StageKind",
    "StageSummary",
    "ToolSummary",
    "ModelSummary",
    "PolicySummary",
    "Workspace",
    "WorkspaceError",
    "WorkspaceEntry",
    "WorkspaceEntryKind",
    "WorkspaceLayout",
    "WorkspaceVersion",
    "MessageSummary",
    "EmailMessage",
    "EmailList",
    "EmailVersion",
    "EmailTools",
    "EmailGatewayError",
    "FakeEmailGateway",
    "OptionalRealEmailGateway",
    "build_optional_email_gateway",
    "BillsOps",
    "ensure_bills_layout",
    "BillStatus",
    "BillsRegistry",
    "BillsRegistryVersion",
    "RegistryBill",
    "AgendaEntry",
    "CalendarProjection",
    "AcceptResult",
    "BillDraft",
    "DraftProposals",
    "InboxEntry",
    "InboxInventory",
    "IntakeVersion",
    "IntakeOps",
    "ensure_intake_layout",
    # Flow-based-programming (FBP) subsystem
    "FbpAgent",
    "FbpAgentConfig",
    "FbpContext",
    "FbpDirective",
    "FbpDriver",
    "FbpResponse",
    "FbpShell",
    "fbp_register_callable",
]