"""Versioned core contracts for Agent-centric.

This package defines the stable, strongly-typed contracts that the control
plane, agents, and verifiers all agree on. Each contract carries an explicit
version so that it can evolve without silently breaking the correctness model.
"""

from .bill import Bill, BillLine, BillTotal, BillVersion
from .bills_registry import (
    AgendaEntry,
    BillsRegistry,
    BillsRegistryVersion,
    BillStatus,
    CalendarProjection,
    MaintainResult,
    RegistryBill,
)
from .capability import Capability
from .component import (
    ChildRef,
    ComponentKind,
    ComponentManifest,
    ComponentVersion,
    EntryDescriptor,
    Provenance,
    RuntimeKind,
    StateDescriptor,
)
from .components_lock import LOCK_SCHEMA, ComponentsLock, LockEntry, LockError
from .critical_path import CpmMetric, CpmVersion, CriticalPathResult, CriticalPathStage
from .email import EmailList, EmailMessage, EmailVersion, MessageSummary
from .handoff import (
    HandoffSchema,
    is_known_type,
    is_valid_schema,
    types_compatible,
    validate_handoff,
    value_matches_type,
)
from .intake import (
    AcceptResult,
    BillDraft,
    DraftProposals,
    InboxEntry,
    InboxInventory,
    IntakeVersion,
)
from .manifest import AgentComponentManifest, AgentManifestVersion
from .model import (
    ModelProvider,
    ModelProviderError,
    ModelProviderVersion,
    ModelResponse,
)
from .parallel import ParallelComposition, ParallelVersion
from .pipeline import PipelineVersion, SequentialComposition, StageSpec
from .policy import Policy, PolicyDecision, PolicyVersion
from .provider import (
    CLOUD_GRANT,
    NOTIFICATION_EMIT_CAPABILITY,
    PROVIDER_SCHEMA,
    NotificationBinding,
    NotificationEvent,
    ObservedResource,
    PlanAction,
    PlanStep,
    Provider,
    ProviderPlan,
    ProviderReport,
    ProviderTarget,
    ProviderTask,
    ProviderVersion,
    ReconcileAction,
    ResourceSpec,
    assert_plan_appliable,
    assert_task_appliable,
    is_plan_pinned,
    plan_provider,
    reconcile_action,
    requires_operator_approval,
    validate_provider,
)
from .replay import ReplayDiff, ReplayResult, ReplayVersion
from .result import Failure, FailureReason, VerifiedResult, VerifiedResultVersion
from .review import (
    DEFAULT_REVIEW_THRESHOLD,
    REVIEW_SCHEMA,
    ReviewItem,
    ReviewResolution,
    ReviewStatus,
    ReviewVersion,
    is_content_hash,
    needs_review,
)
from .service import (
    SERVICE_SCHEMA,
    PinnedRef,
    SecretRef,
    Service,
    ServiceHealth,
    ServiceRefs,
    ServiceReport,
    ServiceTask,
    ServiceVersion,
    TaskBinding,
    TaskKind,
    validate_service,
)
from .summary import (
    ModelSummary,
    PolicySummary,
    RunState,
    StageKind,
    StageSummary,
    SummaryVersion,
    ToolSummary,
    TrajectorySummary,
)
from .task import ResourceEnvelope, TaskSpecification, TaskSpecVersion
from .tool import ToolDescriptor, ToolVersion
from .trajectory import (
    StepRecord,
    StepStatus,
    Trajectory,
    TrajectoryVersion,
)
from .workspace import (
    WorkspaceEntry,
    WorkspaceEntryKind,
    WorkspaceLayout,
    WorkspaceVersion,
)

__all__ = [
    "Capability",
    "ChildRef",
    "ComponentKind",
    "ComponentManifest",
    "ComponentVersion",
    "ComponentsLock",
    "EntryDescriptor",
    "LOCK_SCHEMA",
    "LockEntry",
    "LockError",
    "Provenance",
    "RuntimeKind",
    "StateDescriptor",
    "Bill",
    "BillLine",
    "BillTotal",
    "BillVersion",
    "CpmMetric",
    "CpmVersion",
    "CriticalPathResult",
    "CriticalPathStage",
    "HandoffSchema",
    "is_known_type",
    "is_valid_schema",
    "types_compatible",
    "validate_handoff",
    "value_matches_type",
    "ModelProvider",
    "ModelProviderError",
    "ModelProviderVersion",
    "ModelResponse",
    "AgentComponentManifest",
    "AgentManifestVersion",
    "ParallelComposition",
    "ParallelVersion",
    "PipelineVersion",
    "SequentialComposition",
    "StageSpec",
    "Policy",
    "PolicyDecision",
    "PolicyVersion",
    "ResourceEnvelope",
    "TaskSpecification",
    "TaskSpecVersion",
    "ToolDescriptor",
    "ToolVersion",
    "StepRecord",
    "StepStatus",
    "Trajectory",
    "TrajectoryVersion",
    "Failure",
    "FailureReason",
    "VerifiedResult",
    "VerifiedResultVersion",
    "DEFAULT_REVIEW_THRESHOLD",
    "REVIEW_SCHEMA",
    "ReviewItem",
    "ReviewResolution",
    "ReviewStatus",
    "ReviewVersion",
    "needs_review",
    "is_content_hash",
    "ReplayResult",
    "ReplayDiff",
    "ReplayVersion",
    "SERVICE_SCHEMA",
    "PinnedRef",
    "SecretRef",
    "Service",
    "ServiceHealth",
    "ServiceRefs",
    "ServiceReport",
    "ServiceTask",
    "ServiceVersion",
    "TaskBinding",
    "TaskKind",
    "validate_service",
    "CLOUD_GRANT",
    "NOTIFICATION_EMIT_CAPABILITY",
    "PROVIDER_SCHEMA",
    "NotificationBinding",
    "NotificationEvent",
    "ObservedResource",
    "PlanAction",
    "PlanStep",
    "Provider",
    "ProviderPlan",
    "ProviderReport",
    "ProviderTarget",
    "ProviderTask",
    "ProviderVersion",
    "ReconcileAction",
    "ResourceSpec",
    "assert_plan_appliable",
    "assert_task_appliable",
    "is_plan_pinned",
    "plan_provider",
    "reconcile_action",
    "requires_operator_approval",
    "validate_provider",
    "TrajectorySummary",
    "SummaryVersion",
    "RunState",
    "StageKind",
    "StageSummary",
    "ToolSummary",
    "ModelSummary",
    "PolicySummary",
    "WorkspaceEntry",
    "WorkspaceEntryKind",
    "WorkspaceLayout",
    "WorkspaceVersion",
    "MessageSummary",
    "EmailMessage",
    "EmailList",
    "EmailVersion",
    "BillStatus",
    "BillsRegistry",
    "BillsRegistryVersion",
    "RegistryBill",
    "AgendaEntry",
    "CalendarProjection",
    "MaintainResult",
    "AcceptResult",
    "BillDraft",
    "DraftProposals",
    "InboxEntry",
    "InboxInventory",
    "IntakeVersion",
]
